package nadav.tasher.handasaim.values;

public class Values {
    public static final String prefName = "app_v6";
    public static final String keyPrefName = "keys_v1";
    public static final String pushProvider = "http://h.nockio.com/pushes.json";
    public static final String keyProvider = "http://h.nockio.com/keys/index.php";
    public static final String puzProvider = "http://h.nockio.com";
    public static final String developingUrl = "http://p.nockio.com/handasaim/develop";
    public static final String serviceProvider = "http://handasaim.co.il";
    public static final String scheduleProvider = "http://handasaim.co.il/2017/06/13/%D7%9E%D7%A2%D7%A8%D7%9B%D7%AA-%D7%95%D7%A9%D7%99%D7%A0%D7%95%D7%99%D7%99%D7%9D/index.php";
    public static final String fontName = "varela.ttf";
    public static final String latestFileDate = "latest_file_date_v2";
    public static final String latestFileDateRefresher = "latest_file_date_refresher";
    public static final String breakTime = "break_time";
    public static final String pushService = "push_service";
    public static final String fontColor = "font_color";
    public static final String fontSizeNumber = "font_size_v2";
    public static final String colorA = "colorA";
    public static final String colorB = "colorB";
    public static final String scheduleService = "schedule_service";
    public static final String scheduleFile = "schedule_file";
    public static final String favoriteClass = "favorite_class";
    public static final String favoriteTeacher = "favorite_teacher";
    public static final String messages = "show_messages";
    public static final String devMode = "developer_mode_v1";
    public static final String colorForce = "color_force_v2";
    public static final String pushID = "push_id_";
    public static final String firstLaunch = "first";
    public static final boolean pushDefault = true;
    public static final boolean scheduleDefault = true;
    public static final boolean breakTimeDefault = true;
    public static final boolean devModeDefault = false;
    public static final boolean colorForceDefault = false;
    public static final boolean messagesDefault = true;
    public static final int waitTime = 10;
    public static final int bakedIconColor = 0xffdd8833;
    public static final int refreshLoop = (int) (1000 * 60 * 30);
    public static final int fontSizeDefault = 30;
    public static final int squircleAlpha = 190;
    public static final int defaultColorA = 0xFFb1d4f3;
    public static final int defaultColorB = 0xFFbcb396;
    public static final int navColor = 0x80111111;
    public static final int classCoasterColor = 0xBB333333;
    public static final int classCoasterMarkColor = 0xBB222222;
    public static final int messageColor = classCoasterColor;
    public static final int fontColorDefault = 0xFFFFFFFF;
}
